spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: root
    password: mrdevsonge31!
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000

server:
  port: 8080